### ISSUE TITLE
EXPDAT-004 Notification of upcoming expiry date

### ISSUE THREAD

**Issue by zwerg4** [sw21-tug/Team_25#4]
# user story
**As a** user

**I want** to receive a push notification one day 9:00am before the expiration date

**so that** i am informed.

linked issues: #5 #8

# feature criteria
- [x] display the name on the push notification of the expired item
- [ ] if clicked on the push notification, the app will open and go directly to the detail view #8 
- [ ] there is a placeholder for the detail view as described in #8
- [ ] the view placeholder is in the "List" Tab View
- [ ] There is a X to close the placeholder view
- [ ] show a toast message "this will display %productName%"
 - [ ] coordinate with #15 for storing

# technical stuff
- [ ] trigger a popup
- [ ] second idea: scedule a event each day at 9 am
- [ ] https://developer.android.com/training/notify-user/build-notification
- [ ] https://developer.android.com/topic/libraries/architecture/workmanager  with Job Scheduler
- [ ] retreve this information from the database #5 

# Acceptance criteria
- [ ] runs local without errors
- [ ] commit message contains issue abbreviations
- [ ] commits are squased
- [ ] tests written for it

**Comment by steschi** [comment]
Research Callback even if app is not running:

Callback probably possible using alarms [1] or WorkManager [2], but WorkManager sounds more suitable.

Tutorial for WorkManager can be found in [3] and [4]. 

Best way would probably be to create a `OneTimeTask` for every item scheduled to 9AM on the day before the expiy date.

    // untested pseudo code ;)
    val currentDate = Calendar.getInstance()
    val dueDate = Calendar.getInstance()
    val expiryDate = <from db>
    val uniqueProductIdentifier = "" // some string containing product_id  ... like: "expiry_1"
    // Set Execution around 09:00:00 AM 1 day before expDate
    dueDate.add(Calendar.DAY_OF_YEAR, -1)
   
    val timeDiff = dueDate.timeInMillis — currentDate.timeInMillis
    val dailyWorkRequest = OneTimeWorkRequestBuilder<DailyWorker> 
	    .setInitialDelay(timeDiff, TimeUnit.MILLISECONDS)
        .addTag(product_id).build()
    WorkManager.getInstance(context).enqueue(dailyWorkRequest)




[1] https://developer.android.com/training/scheduling/alarms
[2] https://developer.android.com/topic/libraries/architecture/workmanager )
[3] https://developer.android.com/topic/libraries/architecture/workmanager/basics
[4] https://medium.com/androiddevelopers/workmanager-periodicity-ff35185ff006

**Comment by nicoschmidfbs** [comment]
Research Notifications:

https://developer.android.com/training/notify-user/build-notification

    var builder = NotificationCompat.Builder(this, CHANNEL_ID)
            .setSmallIcon(R.drawable.notification_icon)
            .setContentTitle(<Food will expire>)
            .setContentText(<Your banana will expire tomorrow>)
            .setPriority(NotificationCompat.PRIORITY_DEFAULT)
