### ISSUE TITLE
EXPDAT-008 Detail view for single product

### ISSUE THREAD

**Issue by zwerg4** [sw21-tug/Team_25#8]
# user story

**As a** user

**I want** to see a overview of a single product

**so that** I see the product title, expiry date and the suggestions area.

# feature
- [x] this view will be diplayed if clicked on product in the list from tab "List"
- [x] this view will show Product Name and Exp. Date
- [x] there is a placeholder (black box) for suggestions #7
- [x] it is a stacked view from the "Lists" view #5
- [x] there should be a method with parameter Product_ID , call this to display the detail view on top of  the list view for the given product_id.
- [x] there is a close button to leave this view and resume to the list view tab
- [ ] for later: if we implement this, it will be reused in #4 

# Acceptance criteria
- [ ] runs local without errors
- [ ] commit message contains issue abbreviations
- [ ] commits are squased
- [ ] tests written for it
