### ISSUE TITLE
EXPDAT-009 tab view

### ISSUE THREAD

**Issue by bbruenner** [sw21-tug/Team_25#9]
MERGE with #1 
MERGE with #1 
MERGE with #1 
MERGE with #1 

# user story

**As a** user

**I want** to select different tabs

**so that** different views are shown

linked #2 and #5 and #1

# feature criteria
- [ ] implement tab view naviagtion
- [ ]  app name from #1 should be in the main tab called "Home" with icon "House"
- [ ] input fields from #2 should be in the main tab called "Add" with icon "PLUS"
- [ ] the tab to display the stored data form the database  #5 is called "List"  with "three dotts - unordered list"
- [ ] tab "list" shows an empty lists

# Acceptance criteria
- [ ] runs local without errors
- [ ] commit message contains issue abbreviations
- [ ] commits are squased
- [ ] tests written for it
